2023-07-15 06:53:36,002 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 06:55:07,461 django.request WARNING  Unauthorized: /api/token/
2023-07-15 06:55:15,503 django.request WARNING  Unauthorized: /api/token/
2023-07-15 06:56:20,537 django.request WARNING  Not Found: /ticket/api/ticket-queue/
2023-07-15 06:56:22,076 django.request WARNING  Not Found: /ticket/api/workspace/
2023-07-15 06:56:27,537 django.request WARNING  Not Found: /ticket/api/all-closed-tickets/
2023-07-15 09:04:39,795 django.request WARNING  Bad Request: /api/auth/users/
2023-07-15 09:05:20,613 django.request WARNING  Bad Request: /api/auth/users/
2023-07-15 09:07:08,275 django.request WARNING  Not Found: /api/alt_text_generator/upload_document/
2023-07-15 09:12:56,172 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\urls.py changed, reloading.
2023-07-15 09:12:58,153 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:13:19,965 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\core\urls.py changed, reloading.
2023-07-15 09:13:21,592 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:14:14,213 django.request WARNING  Not Found: /api/alt-text-generator/upload-document/
2023-07-15 09:17:06,265 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\urls.py changed, reloading.
2023-07-15 09:17:07,964 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:17:16,540 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-15 09:17:38,182 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\urls.py changed, reloading.
2023-07-15 09:17:39,866 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:18:11,003 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-15 09:18:22,613 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-15 09:18:31,345 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-15 09:21:42,175 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:22:07,128 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:22:21,639 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:29:31,872 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:29:33,539 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:29:41,627 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:29:43,389 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:30:01,038 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:47:33,404 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:47:35,315 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:47:38,321 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:52:10,948 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:52:46,535 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:54:25,300 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:54:27,001 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:54:33,067 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:56:30,291 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:56:32,102 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:56:36,762 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-15 09:56:38,398 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 09:56:46,211 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:56:53,076 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:57:13,641 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 09:59:33,071 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 10:03:21,970 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-15 10:03:23,632 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:03:30,153 django.request WARNING  Bad Request: /api/alt-text-generator/upload-document/
2023-07-15 10:04:46,183 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-15 10:04:47,841 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:04:57,292 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 31, in api_upload_document
    serializer.save()
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1819, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1743, in as_sql
    value_rows = [
                 ^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1744, in <listcomp>
    [
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1693, in pre_save_val
    return field.pre_save(obj, add=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 334, in generate_filename
    dirname = datetime.datetime.now().strftime(str(self.upload_to))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2023-07-15 10:06:39,567 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-15 10:06:41,227 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:06:47,890 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 31, in api_upload_document
    serializer.save()
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1819, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1743, in as_sql
    value_rows = [
                 ^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1744, in <listcomp>
    [
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1745, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1693, in pre_save_val
    return field.pre_save(obj, add=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\fields\files.py", line 334, in generate_filename
    dirname = datetime.datetime.now().strftime(str(self.upload_to))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2023-07-15 10:08:35,685 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\models.py changed, reloading.
2023-07-15 10:08:37,501 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:09:03,896 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:09:45,675 django.request WARNING  Not Found: /
2023-07-15 10:09:45,824 django.request WARNING  Not Found: /favicon.ico
2023-07-15 10:10:15,300 django.request ERROR    Internal Server Error: /admin/alt_text_generator/document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 272, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 303, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Document has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 336, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 303, in __init__
    super().__init__(*items)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 213, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 285, in lookup_field
    value = attr()
            ^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\models.py", line 14, in __str__
    return self.source.url +"created by " +self.created_by +" at "+ str(self.date_created)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "User") to str
2023-07-15 10:11:12,213 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\models.py changed, reloading.
2023-07-15 10:11:13,875 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 10:11:31,892 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\models.py changed, reloading.
2023-07-15 10:11:33,594 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-15 15:48:58,671 django.request WARNING  Unauthorized: /api/auth/users/me/
2023-07-15 15:58:02,966 django.request WARNING  Unauthorized: /api/auth/users/me/
2023-07-15 16:16:06,626 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-15 16:16:36,892 django.request WARNING  Unauthorized: /api/token/
2023-07-15 16:16:46,426 django.request WARNING  Unauthorized: /api/token/
2023-07-15 16:19:25,470 django.request WARNING  Not Found: /
2023-07-15 16:19:25,608 django.request WARNING  Not Found: /favicon.ico
2023-07-16 05:19:28,354 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 05:19:32,073 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:38:30,560 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-16 06:38:35,131 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:38:38,728 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-16 06:38:40,452 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:44:19,237 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-16 06:44:21,115 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:44:33,242 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 27, in api_upload_document
    return Response(serializer.data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\relations.py", line 378, in to_representation
    assert 'request' in self.context, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: `HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
2023-07-16 06:45:52,522 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-16 06:45:54,248 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:49:24,108 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\serializers.py changed, reloading.
2023-07-16 06:49:25,978 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 06:52:15,370 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 08:56:52,224 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:23:29,486 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:23:31,177 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:25:00,269 django.request WARNING  Unauthorized: /api/alt-text-generator/upload-document/
2023-07-16 09:25:33,828 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 30, in api_upload_document
    lst = figure_predictions(settings.BASE_DIR+serializer.data.source)
                                               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ReturnDict' object has no attribute 'source'
2023-07-16 09:26:42,753 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:26:44,505 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:26:49,109 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:26:50,824 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:28:02,702 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:28:04,476 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:28:10,448 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 30, in api_upload_document
    lst = figure_predictions(settings.BASE_DIR+serializer.data['source'])
                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
2023-07-16 09:28:59,164 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:29:00,909 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:29:36,913 django.request ERROR    Internal Server Error: /api/alt-text-generator/upload-document/
Traceback (most recent call last):
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\views.py", line 30, in api_upload_document
    lst = figure_predictions(str(settings.BASE_DIR)+serializer.data['source'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\alt_text_prediction.py", line 219, in figure_predictions
    content,figures_list = read_docx_file(file_path)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\backend\alt_text_generator\alt_text_prediction.py", line 13, in read_docx_file
    doc = Document(file_path)
          ^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
                    ^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\docx\opc\package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aptara\alt_text_generator\.venv\Lib\site-packages\docx\opc\phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'D:\aptara\alt_text_generator\backend/media/uploads/0_1N9r0c5.docx'
2023-07-16 09:33:34,971 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:33:37,411 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:38:20,934 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:38:22,685 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:41:22,142 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:41:23,897 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-16 09:41:56,047 django.utils.autoreload INFO     D:\aptara\alt_text_generator\backend\alt_text_generator\views.py changed, reloading.
2023-07-16 09:41:57,800 django.utils.autoreload INFO     Watching for file changes with StatReloader
